@startgantt Week 6 Plan
Project starts 2024-11-4
[Finish Architecture Writeup] starts 2024-11-3 and ends 2024-11-7
[Upload Documents to Website] starts 2024-11-4 and ends 2024-11-7
[Finish Method Selection & Planning] starts 2024-11-4 and ends 2024-11-7
[Add Final Building Improvements] starts 2024-11-4 and ends 2024-11-5
[Assessment 1 Submission Goal] happens at 2024-11-8
[Final Submission Deadline] happens at 2024-11-11
@endgantt