@startgantt Week 3 Plan
Project starts 2024-10-7
[Monday meeting] starts 2024-10-7 and ends 2024-10-7
[Risks write up] starts 2024-10-7 and lasts 7 days
[Start Requirements] starts 2024-10-10 and lasts 9 days
[Architecture] starts 2024-10-10 and lasts 5 days
[Client meeting] starts 2024-10-10 and ends 2024-10-10
[Thursday Meeting] starts 2024-10-10 and ends 2024-10-10
@endgantt