@startuml Project Structure

abstract class Game
{
    + render(): void
    + resize(): void
}

class gameState
{
    + {static} currentScreen: Screen
    + {static} paused: boolean
    + {static} gameOver: boolean
    + {static} settings: Settings
}

class Main extends Game
{
    + render(): void
    + resize(): void
}

@enduml