[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

jacoco {
  toolVersion = "0.8.12"
}

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  testImplementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
  testImplementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

test {
  useJUnitPlatform()
  jacoco {
    destinationFile = layout.buildDirectory.file("jacoco/jacocoTest.exec").get().asFile
  }
  // Enable debugging for tests
  if (project.hasProperty('debug') && project.debug == 'true') {
      jvmArgs += ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"]
  }
}

testing {
  suites {
    test {
      useJUnitJupiter()
    }
    integrationTest(JvmTestSuite) {
      dependencies {
        implementation project()
        implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
        implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
      }
      targets {
        all {
          testTask.configure {
            shouldRunAfter(test)
            useJUnitJupiter()
            if (project.hasProperty('debug') && project.debug == 'true') {
              jvmArgs += ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"]
            }
          }
        }
      }
    }
  }
}

jacocoTestReport {
  dependsOn(test)
  reports {
    html.required = true
  }
}
